2021-09-12 14:34:27.1179|INFO|Info|User Iserial:19
2021-09-12 14:34:27.1599|ERROR|Info|{"Message":"An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.","Data":{},"InnerException":{"Detail":{"InnerException":{"InnerException":null,"Message":"The member with identity '' does not exist in the metadata collection.\r\nParameter name: identity","StackTrace":"   at System.Data.Metadata.Edm.MemberCollection.GetValue(String identity, Boolean ignoreCase)\r\n   at System.Data.Metadata.Edm.MemberCollection.get_Item(String identity)\r\n   at System.Data.Metadata.Edm.ReadOnlyMetadataCollection`1.get_Item(String identity)\r\n   at System.Data.Metadata.Edm.FilteredReadOnlyMetadataCollection`2.get_Item(String identity)\r\n   at System.Data.Metadata.Edm.FilteredReadOnlyMetadataCollection`2.System.Data.Metadata.Edm.IBaseList<TBase>.get_Item(String identity)\r\n   at System.Data.Mapping.Update.Internal.DynamicUpdateCommand.Execute(UpdateTranslator translator, EntityConnection connection, Dictionary`2 identifierValues, List`1 generatedValues)\r\n   at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)","Type":"System.ArgumentException"},"Message":"An error occurred while updating the entries. See the inner exception for details.","StackTrace":"   at CCWFM.Web.Service.CRUD_ManagerService.AddAllNewAccessoriesAttributes(tbl_AccessoryAttributesHeader header, List`1 details, Boolean isSizeInHeader, Int32 userIserial) in D:\\CCWFM\\CCWFM.Web\\Service\\Operations\\AccessoriesOperations.cs:line 56\r\n   at SyncInvokeAddAllNewAccessoriesAttributes(Object , Object[] , Object[] )\r\n   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)\r\n   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)","Type":"System.Data.UpdateException"},"Action":"http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher/fault","Code":{"IsPredefinedFault":true,"IsSenderFault":false,"IsReceiverFault":true,"Namespace":"http://www.w3.org/2003/05/soap-envelope","Name":"Receiver","SubCode":{"IsPredefinedFault":false,"IsSenderFault":false,"IsReceiverFault":false,"Namespace":"http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher","Name":"InternalServiceFault","SubCode":null}},"Message":"An error occurred while updating the entries. See the inner exception for details.","Reason":{"Translations":[{"XmlLang":"en-US","Text":"An error occurred while updating the entries. See the inner exception for details."}]},"Data":{},"InnerException":null,"StackTrace":"   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)\r\n   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)\r\n   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)\r\n   at System.ServiceModel.ClientBase`1.ChannelBase`1.EndInvoke(String methodName, Object[] args, IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.CRUD_ManagerServiceClientChannel.EndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.CCWFM.CRUDManagerService.CRUD_ManagerService.EndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.OnEndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at System.ServiceModel.ClientBase`1.OnAsyncCallCompleted(IAsyncResult result)"},"StackTrace":"   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()\r\n   at CCWFM.CRUDManagerService.AddAllNewAccessoriesAttributesCompletedEventArgs.get_Result()\r\n   at CCWFM.ViewModel.AccessoriesViewModel.AccessoriesViewModel.<SaveAccessories>b__4_0(Object s, AddAllNewAccessoriesAttributesCompletedEventArgs sv)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.OnAddAllNewAccessoriesAttributesCompleted(Object state)"}
2021-09-12 14:34:58.1273|INFO|Info|User Iserial:19
2021-09-12 14:34:58.1273|ERROR|Info|{"Message":"An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.","Data":{},"InnerException":{"Detail":{"InnerException":{"InnerException":null,"Message":"The member with identity '' does not exist in the metadata collection.\r\nParameter name: identity","StackTrace":"   at System.Data.Metadata.Edm.MemberCollection.GetValue(String identity, Boolean ignoreCase)\r\n   at System.Data.Metadata.Edm.MemberCollection.get_Item(String identity)\r\n   at System.Data.Metadata.Edm.ReadOnlyMetadataCollection`1.get_Item(String identity)\r\n   at System.Data.Metadata.Edm.FilteredReadOnlyMetadataCollection`2.get_Item(String identity)\r\n   at System.Data.Metadata.Edm.FilteredReadOnlyMetadataCollection`2.System.Data.Metadata.Edm.IBaseList<TBase>.get_Item(String identity)\r\n   at System.Data.Mapping.Update.Internal.DynamicUpdateCommand.Execute(UpdateTranslator translator, EntityConnection connection, Dictionary`2 identifierValues, List`1 generatedValues)\r\n   at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)","Type":"System.ArgumentException"},"Message":"An error occurred while updating the entries. See the inner exception for details.","StackTrace":"   at CCWFM.Web.Service.CRUD_ManagerService.AddAllNewAccessoriesAttributes(tbl_AccessoryAttributesHeader header, List`1 details, Boolean isSizeInHeader, Int32 userIserial) in D:\\CCWFM\\CCWFM.Web\\Service\\Operations\\AccessoriesOperations.cs:line 56\r\n   at SyncInvokeAddAllNewAccessoriesAttributes(Object , Object[] , Object[] )\r\n   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)\r\n   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)\r\n   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)","Type":"System.Data.UpdateException"},"Action":"http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher/fault","Code":{"IsPredefinedFault":true,"IsSenderFault":false,"IsReceiverFault":true,"Namespace":"http://www.w3.org/2003/05/soap-envelope","Name":"Receiver","SubCode":{"IsPredefinedFault":false,"IsSenderFault":false,"IsReceiverFault":false,"Namespace":"http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher","Name":"InternalServiceFault","SubCode":null}},"Message":"An error occurred while updating the entries. See the inner exception for details.","Reason":{"Translations":[{"XmlLang":"en-US","Text":"An error occurred while updating the entries. See the inner exception for details."}]},"Data":{},"InnerException":null,"StackTrace":"   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)\r\n   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)\r\n   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)\r\n   at System.ServiceModel.ClientBase`1.ChannelBase`1.EndInvoke(String methodName, Object[] args, IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.CRUD_ManagerServiceClientChannel.EndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.CCWFM.CRUDManagerService.CRUD_ManagerService.EndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.OnEndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at System.ServiceModel.ClientBase`1.OnAsyncCallCompleted(IAsyncResult result)"},"StackTrace":"   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()\r\n   at CCWFM.CRUDManagerService.AddAllNewAccessoriesAttributesCompletedEventArgs.get_Result()\r\n   at CCWFM.ViewModel.AccessoriesViewModel.AccessoriesViewModel.<SaveAccessories>b__4_0(Object s, AddAllNewAccessoriesAttributesCompletedEventArgs sv)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.OnAddAllNewAccessoriesAttributesCompleted(Object state)"}
2021-09-12 14:45:34.2193|INFO|Info|User Iserial:19
2021-09-12 14:45:34.2313|ERROR|Info|{"Message":"An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.","Data":{},"InnerException":{"Message":"The HTTP request to 'http://localhost:18559/Service/CRUD_ManagerService.svc' has exceeded the allotted timeout. The time allotted to this operation may have been a portion of a longer timeout.","Data":{},"InnerException":{"Status":6,"Response":null,"Message":"","Data":{},"InnerException":{"Status":6,"Response":null,"Message":"","Data":{},"InnerException":null,"StackTrace":"   at System.Net.Browser.BrowserHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Browser.BrowserHttpWebRequest.<>c__DisplayClassa.<EndGetResponse>b__9(Object sendState)\r\n   at System.Net.Browser.AsyncHelper.<>c__DisplayClass4.<BeginOnUI>b__0(Object sendState)"},"StackTrace":"   at System.Net.Browser.AsyncHelper.BeginOnUI(SendOrPostCallback beginMethod, Object state)\r\n   at System.Net.Browser.BrowserHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelAsyncRequest.CompleteGetResponse(IAsyncResult result)"},"StackTrace":"   at System.ServiceModel.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)\r\n   at System.ServiceModel.ClientBase`1.ChannelBase`1.EndInvoke(String methodName, Object[] args, IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.CRUD_ManagerServiceClientChannel.EndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.CCWFM.CRUDManagerService.CRUD_ManagerService.EndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.OnEndAddAllNewAccessoriesAttributes(IAsyncResult result)\r\n   at System.ServiceModel.ClientBase`1.OnAsyncCallCompleted(IAsyncResult result)"},"StackTrace":"   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()\r\n   at CCWFM.CRUDManagerService.AddAllNewAccessoriesAttributesCompletedEventArgs.get_Result()\r\n   at CCWFM.ViewModel.AccessoriesViewModel.AccessoriesViewModel.<SaveAccessories>b__4_0(Object s, AddAllNewAccessoriesAttributesCompletedEventArgs sv)\r\n   at CCWFM.CRUDManagerService.CRUD_ManagerServiceClient.OnAddAllNewAccessoriesAttributesCompleted(Object state)"}
